### PR TITLE
Fix 317

### PR DESCRIPTION
**Pull request by nmccready**
Memory leak fixes and tests.

### CODE REVIEW

**Comment by nmccready** [comment]
@phated review fixes #317

**Comment by nmccready** [comment]
Looking into Travis

**Comment by phated** [comment]
@nmccready It's C stuff. Is there no way to test the memory leaks without it?

**Comment by nmccready** [comment]
@phated I think I know the problem. I already did this update for travis in the debug-fabulous project. Anyway travis made things more complicated and we need to tell it to explicitly install C libs for node.

**Comment by nmccready** [comment]
See [travis.yml](https://github.com/nmccready/debug-fabulous/commit/0d31daaac7d4cce8ec6f2601037c7d907461488d#diff-354f30a63fb0907d4ad57269548329e3)

**Comment by nmccready** [comment]
Ill fix it.

**Comment by nmccready** [comment]
Now looks like npm is failing to run or install on node 0.12 and 0.10.

**Comment by phated** [comment]
Don't install npm@latest... it no longer works on 0.10  - Either lock it at 4 or use the version it ships with.

**Comment by nmccready** [comment]
ugghhh.... I will keep digging or remove the memwatch-next stuff.

**Comment by nmccready** [comment]
@phated finally fixed.. gave up on memwatch-next and all that.

**Comment by phated** [comment]
@nmccready not much for me to review now 😛  looks good to ship!

**Pull request merged**
