### PR TITLE
#210 Fix - existing "sourceRoot" on source maps is ignored

### PR DESCRIPTION
**Pull request by issidorov**
Fix bug. Incorrect source file path with setted sorceRoot. Use loadMaps == true

### CODE REVIEW

**Comment by phated** [comment]
Interesting solution.  @rbuckton what do you think about this?

@nmccready cc'd also.

**Comment by phated** [comment]
Looks like a bunch of tests broke.

**Comment by rbuckton** [comment]
I'd be wary of using a `path`-only approach to resolve sources. `path` doesn't understand URLs, including file-based URLs (e.g. `file:///`). For example, one of the failing tests is reporting this:

```
      expected: |-
        [ 'helloworld.js', 'http://example2.com/test1.js' ]
      actual: |-
        [ 'http:/example.com/helloworld.js', 'http:/example.com/http:/example2.com/test1.js' ]
      at: DestroyableTransform.<anonymous> (/home/travis/build/gulp-sourcemaps/gulp-sourcemaps/test/init.js:325:7)
```

Note the actual result is `http:/` instead of `http://`.

You need to be able to check whether the `sourceRoot` is a URL. If it is a `file://` URL, convert it to a local path first. If its some other scheme (`http:`, `https:` etc.), perhaps use the `url` module to resolve the path?

**Comment by rbuckton** [comment]
An example of where I proposed a similar fix to address this for the `source-map-support` package is here: https://github.com/evanw/node-source-map-support/pull/126/files#diff-f332e9a051ea7f7b602a3d633c506d30R85

**Comment by phated** [comment]
@rbuckton alright, do you think the technique used here (resolving the `sources` against `sourceRoot` and then removing the `sourceRoot`) is the right technique for solving this?

**Comment by rbuckton** [comment]
Honestly, I'm not sure at this point. I filed that bug almost a year ago and I am unsure what has changed since then. There seems to have been a significant refactoring and this may no longer be an issue. It seems that most places that need it are already referring to `sourceRoot`. It may not be worth the change.

**Comment by nmccready** [comment]
Sorry this fell off my radar. I have been consumed with my job as of late and less open source. I think we should start with some unit tests which proves that this current problem still exists. Once we have that then we can try and back fill this fix. We can leave this open or just move it to an issue.

**Comment by nmccready** [comment]
Closing this as it's pretty old and stale.

**Pull request closed without merging**
